#!/bin/bash

# Place script in /etc/cron.daily
# Generate a vnstati bandwidth usage png, append the date, and save it to Dropbox
vnstati -s -i wlp4s0 -o /home/seven/Dropbox/Kubuntu/network-log-"`date +"%d-%m-%Y"`".png
